### ISSUE TITLE
Is this module python 3 compliant?

### ISSUE THREAD

**Issue by webquest-nz** [kylef/irctk#3]
From looking at the code it looks like it uses asyncio so does that mean it's non blocking?  I am looking for something to replace the IRC module in Twisted networking framework which seems to have not provided full python 3 support and in fact the IRC module of twisted just refuses to work on python 3.

**Comment by kylef** [comment]
Yes, requires modern 3.6 onwards as per https://github.com/kylef/irctk/blob/master/pyproject.toml#L10.

It's built on top of asyncio (in newer versions of irctk) so the work can be scheduled in the asyncio event loop.

**Comment by kylef** [comment]
If you're
